### PR TITLE
Add Polly's records

### PR DESCRIPTION
**Pull request by FuzzyLitchi**
I wrote some Rust software[1], which on my machine is about 1000x faster than your python implementation. I'm getting 4.6 MH/s. I think if we really want to get some nice md5 hashes, we should work on a GPU implementation of this program.

1: https://github.com/FuzzyLitchi/nice-md5s-rs

### CODE REVIEW

**Comment by zvibazak** [comment]
Thanks!

**Comment by ElijahBare** [comment]
Cuda implementation would be cool. I don't understand how we would get it though, would we have to iterate through every possible char combo until we hit each best match? Up to 32 characters at least.

**Comment by zvibazak** [comment]
We could also pray... :) @ElijahBare

**Comment by ElijahBare** [comment]
Ha. I'll start a cuda implementation. If you want talk add me on discord: JackOfSpades#3001

**Pull request merged**
